### ISSUE TITLE
Improve auto-complete suggestor

### ISSUE THREAD

**Issue by avive** [spacemeshos/smrepl#29]
# Motivation
This project uses [go-prompt](https://github.com/c-bata/go-prompt) for auto-completion and suggestions. Currently, all commands for all features are suggested resulting in a very large suggestor that is often beyond the size of the user's terminal window. 

![auto-complete](https://user-images.githubusercontent.com/96002/123037975-42bd8980-d3f8-11eb-9622-4924a73ea76d.PNG)

 
# The Task
Refactor the suggestor to auto-complete to category names and once a category prefix was inputed, suggest the category's commands. 

High-level command categories (first stage auto-complete):

```
wallet  // wallet related commands
account // account related commands - only available when a wallet is open
state // global state commands
status // should likely be merged with state
mesh // mesh data
smesher // smesher related commands
pos // proof of spacetime setup related commands
dbg // dbg commands
```

Once user typed or selected one of these categories, the auto-completer should only display the commands for the category.
For full list of commands, see: https://github.com/spacemeshos/smrepl/blob/smesher-api/repl/repl.go

**Comment by avive** [comment]
By working on this task you will earn the Spacemesh contributor NFT https://gitcoin.co/kudos/5191/spacemesh_top_contributor

**Comment by avive** [comment]
Fixed in #31

**Comment by Soptq** [comment]
Hi @avive, would you please help me get that spacemesh contributor NFT?

**Comment by avive** [comment]
Sure - just send me your eth address and I'll mint one for you!

**Comment by Soptq** [comment]
Thanks! sent it to your Gmail!
