### ISSUE TITLE
Support non-interactive CLI

### ISSUE THREAD

**Issue by tal-m** [spacemeshos/smrepl#9]
I think it would be helpful to have a non-interactive CLI. This makes it much easier to use in external scripts and to run one-off commands. 

I'd expect something like

    cli_wallet info

to output the info to stdout, while 
    
    cli_wallet tx me 0x1234 70

Should send 70 SMD from the local account named "me" to account 0x1234

**Comment by avive** [comment]
Yes, @moshababo wanted to do something like this as well. What we have now is far from ideal and barebones.

**Comment by moshababo** [comment]
It's a different tool, but one that is probably more appropriate. For user-friendliness, we have the Wallet App, thus we don't need this tool cover that use case as well, in the cost of not being compatible with plain scripting. 

So we definitely need a non-interactive CLI tool as Tal suggested (except perhaps a lock/unlock phase). As discussed, I suggest that it will replace the current tool, and will be called `smcli`.

**Comment by avive** [comment]
I'm going to close this issue. This app is designed to be an interactive repl and not a non-interactive cli. It will be nice to have a non-interactive cli but a repl is quite different. Both a non-interactive cli and smrepl can likely share code when such a cli is going to be built. The focus for release 0.2 of smrepl is interactive usage.
